"""
Utility functions for generating and validating signed email verification tokens.

Tokens are created using `itsdangerous.URLSafeTimedSerializer` with the
application's SECRET_KEY, and include a timestamp signature to enforce token
expiration. These tokens are typically sent by email to verify user accounts.
"""
from itsdangerous import URLSafeTimedSerializer
from flask import current_app

def generate_verification_token(email: str) -> str:
    """
    Generate a signed verification token from the user's email address.

    Args:
        email: The email address to sign and encode into the token.

    Returns:
        A time-signed, URL-safe token that can later be validated using
        `confirm_verification_token`.
    """
    s = URLSafeTimedSerializer(current_app.config["SECRET_KEY"])
    return s.dumps(email, salt="email-verification")

def confirm_verification_token(token: str, expiration=3600):
    """
    Validate a signed verification token and return the associated email.

    Args:
        token: The verification token originally generated by
            `generate_verification_token`.
        expiration: Maximum allowed token age (in seconds). Defaults to one hour.

    Returns:
        The email address embedded in the token if it is valid and not expired.
        None if the token is invalid or the signature has expired.
    """
    s = URLSafeTimedSerializer(current_app.config["SECRET_KEY"])
    try:
        email = s.loads(token, salt="email-verification", max_age=expiration)
        return email
    except Exception:
        return None
