"""Different types enumeration definition.

This module defines the different types enum, which is used to categorize 
different types of entities in the system
"""

import enum


class UserType(enum.Enum):
    """Enumeration for different user roles in the system."""

    # Coordinator role: typically manages the system or courses
    COORDINATOR = "Coordinator"

    # Teacher role: represents instructors assigned to classes
    TEACHER = "Teacher"

    # Student role: represents learners enrolled in courses
    STUDENT = "Student"

class ExamStatus(enum.Enum):
    """Enumeration for different exam statuses in the system."""

    # Pending review status: exam has been generated by a Teacher but has not yet been reviewed by a Coordinator
    PENDING_REVIEW = "Pending Review"

    # On review status: exam is currently being reviewed by a Coordinator
    ON_REVIEW = "On Review"

    # Accepted status: exam has been reviewed and accepted by a Coordinator
    ACCEPTED = "Accepted"

    # Pending correction status: exam has been reviewed by a Coordinator and is awaiting correction by a Teacher
    PENDING_CORRECTION = "Pending Correction"

    # On correction status: exam is currently being corrected by a Teacher
    ON_CORRECTION = "On Correction"

    # Student exam status: exam has been generated by a Student and it doesn't require any review or correction
    STUDENT_EXAM = "Student Exam"

    # Test exam status: used for testing purposes
    TEST_EXAM = "Test Exam"

class ExerciseArchetype(enum.Enum):
    """Enumeration for different exercise archetypes in the system."""

    # Word transformation archetype: exercise where a word must be transformed using a given prefix or suffix
    WORD_TRANSFORMATION = "Word Transformation"

    # Key word transformation archetype: exercise where a sentence must be transformed using a given keyword
    KEY_WORD_TRANSFORMATION = "Key Word Transformation"

    # Test archetype: used for testing purposes
    TEST_ARCHETYPE = "Test archetype"
