"""Different types enumeration definition.

This module defines the different types enum, which is used to categorize 
different types of entities in the system
"""

import enum


class UserType(enum.Enum):
    """Enumeration for different user roles in the system."""

    # Coordinator role: typically manages the system or courses
    COORDINATOR = "Coordinator"

    # Teacher role: represents instructors assigned to classes
    TEACHER = "Teacher"

    # Student role: represents learners enrolled in courses
    STUDENT = "Student"

class ExamStatus(enum.Enum):
    """Enumeration for different exam statuses in the system."""

    # Pending review status: exam has been generated by a Teacher but has not yet been reviewed by a Coordinator
    PENDING_REVIEW = "Pending Review"

    # On review status: exam is currently being reviewed by a Coordinator
    ON_REVIEW = "On Review"

    # Accepted status: exam has been reviewed and accepted by a Coordinator
    ACCEPTED = "Accepted"

    # Pending correction status: exam has been reviewed by a Coordinator and is awaiting correction by a Teacher
    PENDING_CORRECTION = "Pending Correction"

    # On correction status: exam is currently being corrected by a Teacher
    ON_CORRECTION = "On Correction"

    # Student exam status: exam has been generated by a Student and it doesn't require any review or correction
    STUDENT_EXAM = "Student Exam"

class ExerciseArchetype(enum.Enum):
    """Enumeration for different exercise archetypes in the system."""

    # Multiple choice archetype: exercise with multiple options where only one is correct
    MULTIPLE_CHOICE = "Multiple Choice"

    # True/False archetype: exercise with two options, true or false
    TRUE_FALSE = "True/False"

    # Completion archetype: exercise where the user must fill in the blanks
    COMPLETION = "Completion"

    # Short answer archetype: exercise where the user must provide a brief answer
    SHORT_ANSWER = "Short Answer"

    # Connecting archetype: exercise where the user must connect related items
    CONNECTING = "Connecting"

    # Matching archetype: exercise where the user must match items from two columns
    MATCHING = "Matching"

    # Ordering archetype: exercise where the user must arrange items in a specific order
    ORDERING = "Ordering"
